[comment]: <> (README.md is generated)

![Maintenance](https://img.shields.io/badge/maintenance-activly--developed-brightgreen.svg)

# {{crate}}

{{readme}}

## Development

### Fuzzing

Install cargo-fuzz:

```
$ cargo install cargo-fuzz
```

Run the fuzzer:

```
$ cargo +nightly fuzz run fuzz_target_1
```

### Documentation

Slyce is documented using rust documentation comments throughout the source files.
The README.md is generated by combining the README.tpl file and the rustdoc comments:

```
$ cargo install cargo-readme
$ ./scripts/gen-readme.sh
```

The README.tpl file should contain the documentation about the project governance and tooling,
while the inline rustdoc comments should document what the project actually does from the POV
of a user consuming the crate(s).

## License

{{license}}
